$ErrorActionPreference = "Stop"
$dir = "messages"
if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir | Out-Null }

function Write-Utf8NoBom {
    param([string]$Path, [string]$Content)
    $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($Path, $Content, $utf8NoBom)
    Write-Host "Wrote $Path"
}

$files = @{}

$files["it"] = @'
{"HomePage": {"scheduleHeading": "Prenota una visita e ottieni uno sconto", "country": "Paese", "selectCountry": "Seleziona il paese", "city": "Città", "selectCity": "Seleziona la città", "store": "Negozio", "selectStore": "Seleziona il negozio", "viewStoreCta": "Vedi il negozio e prenota la visita", "forCustomers": "Per i clienti", "customersText": "Con lo <strong>Scheduled Visit Discount (SVD)</strong>, prenoti una visita al negozio in anticipo. Se arrivi puntuale ed effettui un acquisto, ricevi uno sconto concordato in anticipo. Niente attese, niente incertezze, prezzi migliori.", "forStoreManagers": "Per i negozianti", "managersText": "SVD trasforma le visite pianificate in una domanda prevedibile. Sai chi arriva, quando e perché. Gli sconti sono compensati da una maggiore conversione, operazioni più fluide e un migliore utilizzo del personale e degli spazi.", "heroHeadline": "Gli sconti non vendono.", "heroAccent": "L'impegno sì.", "heroSubline": "Trasforma i curiosi in clienti impegnati."}}
'@

$files["fr"] = @'
{"HomePage": {"scheduleHeading": "Réservez une visite et obtenez une réduction", "country": "Pays", "selectCountry": "Sélectionnez un pays", "city": "Ville", "selectCity": "Sélectionnez une ville", "store": "Boutique", "selectStore": "Sélectionnez une boutique", "viewStoreCta": "Voir la boutique et réserver une visite", "forCustomers": "Pour les clients", "customersText": "Avec le <strong>Scheduled Visit Discount (SVD)</strong>, vous réservez une visite en magasin à l'avance. Si vous arrivez à l'heure et effectuez un achat, vous recevez une réduction convenue à l'avance. Pas d'attente, pas d'incertitude, de meilleurs prix.", "forStoreManagers": "Pour les commerçants", "managersText": "Le SVD transforme les visites planifiées en demande prévisible. Vous savez qui vient, quand et pourquoi. Les réductions sont compensées par une meilleure conversion, des opérations plus fluides et une meilleure utilisation du personnel et de l'espace.", "heroHeadline": "Les réductions ne vendent pas.", "heroAccent": "L'engagement, si.", "heroSubline": "Transformez les curieux en clients engagés."}}
'@

$files["de"] = @'
{"HomePage": {"scheduleHeading": "Termin vereinbaren und Rabatt erhalten", "country": "Land", "selectCountry": "Land auswählen", "city": "Stadt", "selectCity": "Stadt auswählen", "store": "Geschäft", "selectStore": "Geschäft auswählen", "viewStoreCta": "Geschäft ansehen und Termin buchen", "forCustomers": "Für Kunden", "customersText": "Mit dem <strong>Scheduled Visit Discount (SVD)</strong> buchen Sie einen Besuch im Geschäft im Voraus. Wenn Sie pünktlich erscheinen und einen Kauf tätigen, erhalten Sie einen vorher vereinbarten Rabatt. Kein Warten, keine Unsicherheit, bessere Preise.", "forStoreManagers": "Für Geschäftsinhaber", "managersText": "SVD verwandelt geplante Besuche in vorhersehbare Nachfrage. Sie wissen, wer kommt, wann und warum. Die Rabatte werden durch höhere Konversion, reibungslosere Abläufe und bessere Nutzung von Personal und Raum ausgeglichen.", "heroHeadline": "Rabatte verkaufen nicht.", "heroAccent": "Verbindlichkeit schon.", "heroSubline": "Verwandeln Sie Schaufensterbummler in engagierte Kunden."}}
'@

$files["nl"] = @'
{"HomePage": {"scheduleHeading": "Boek een bezoek en krijg korting", "country": "Land", "selectCountry": "Selecteer land", "city": "Stad", "selectCity": "Selecteer stad", "store": "Winkel", "selectStore": "Selecteer winkel", "viewStoreCta": "Bekijk winkel en boek bezoek", "forCustomers": "Voor klanten", "customersText": "Met de <strong>Scheduled Visit Discount (SVD)</strong> boek je van tevoren een winkelbezoek. Als je op tijd komt en iets koopt, krijg je een vooraf afgesproken korting. Geen wachten, geen onzekerheid, betere prijzen.", "forStoreManagers": "Voor winkeliers", "managersText": "SVD verandert geplande bezoeken in voorspelbare vraag. Je weet wie er komt, wanneer en waarom. De kortingen worden gecompenseerd door hogere conversie, soepelere bedrijfsvoering en beter gebruik van personeel en ruimte.", "heroHeadline": "Kortingen verkopen niet.", "heroAccent": "Toewijding wel.", "heroSubline": "Maak van etalagekijkers toegewijde klanten."}}
'@

$files["et"] = @'
{"HomePage": {"scheduleHeading": "Broneeri külastus ja saa allahindlus", "country": "Riik", "selectCountry": "Vali riik", "city": "Linn", "selectCity": "Vali linn", "store": "Pood", "selectStore": "Vali pood", "viewStoreCta": "Vaata poodi ja broneeri külastus", "forCustomers": "Klientidele", "customersText": "<strong>Scheduled Visit Discount (SVD)</strong> abil broneerid poekülastuse ette. Kui jõuad õigel ajal kohale ja teed ostu, saad eelnevalt kokkulepitud allahindluse. Ei mingit ootamist, ei mingit ebakindlust, paremad hinnad.", "forStoreManagers": "Poeomanikele", "managersText": "SVD muudab planeeritud külastused prognoositavaks nõudluseks. Tead, kes tuleb, millal ja miks. Allahindlused tasakaalustatakse suurema konversiooni, sujuvama töö ning personali ja ruumi parema kasutamisega.", "heroHeadline": "Allahindlused ei müü.", "heroAccent": "Pühendumus müüb.", "heroSubline": "Muuda vaateaknavaatajad pühendunud klientideks."}}
'@

$files["lv"] = @'
{"HomePage": {"scheduleHeading": "Piesakies apmeklējumam un saņem atlaidi", "country": "Valsts", "selectCountry": "Izvēlies valsti", "city": "Pilsēta", "selectCity": "Izvēlies pilsētu", "store": "Veikals", "selectStore": "Izvēlies veikalu", "viewStoreCta": "Skatīt veikalu un pieteikt apmeklējumu", "forCustomers": "Klientiem", "customersText": "Izmantojot <strong>Scheduled Visit Discount (SVD)</strong>, tu iepriekš piesaki veikala apmeklējumu. Ja ierodies laikā un veic pirkumu, saņem iepriekš saskaņotu atlaidi. Bez gaidīšanas, bez neskaidrības, labākas cenas.", "forStoreManagers": "Veikalu īpašniekiem", "managersText": "SVD pārvērš plānotos apmeklējumus prognozējamā pieprasījumā. Tu zini, kas nāks, kad un kāpēc. Atlaides kompensē augstāka konversija, vienmērīgāka darbība un labāka personāla un telpu izmantošana.", "heroHeadline": "Atlaides nepārdod.", "heroAccent": "Apņemšanās gan.", "heroSubline": "Pārvērt skatlogu vērotājus par apņēmīgiem klientiem."}}
'@

$files["lt"] = @'
{"HomePage": {"scheduleHeading": "Užsisakykite apsilankymą ir gaukite nuolaidą", "country": "Šalis", "selectCountry": "Pasirinkite šalį", "city": "Miestas", "selectCity": "Pasirinkite miestą", "store": "Parduotuvė", "selectStore": "Pasirinkite parduotuvę", "viewStoreCta": "Žiūrėti parduotuvę ir užsisakyti apsilankymą", "forCustomers": "Klientams", "customersText": "Naudodami <strong>Scheduled Visit Discount (SVD)</strong>, iš anksto užsisakote apsilankymą parduotuvėje. Jei atvykstate laiku ir atliekate pirkinį, gaunate iš anksto sutartą nuolaidą. Jokio laukimo, jokio neapibrėžtumo, geresnės kainos.", "forStoreManagers": "Parduotuvių savininkams", "managersText": "SVD paverčia suplanuotus apsilankymus nuspėjama paklausa. Žinote, kas ateis, kada ir kodėl. Nuolaidas kompensuoja didesnis konversijos rodiklis, sklandesnė veikla ir geresnis personalo bei erdvės panaudojimas.", "heroHeadline": "Nuolaidos neparduoda.", "heroAccent": "Įsipareigojimas – taip.", "heroSubline": "Paverskite vitrinų žiūrinėtojus įsipareigojusiais klientais."}}
'@

$files["cs"] = @'
{"HomePage": {"scheduleHeading": "Naplánujte návštěvu a získejte slevu", "country": "Země", "selectCountry": "Vyberte zemi", "city": "Město", "selectCity": "Vyberte město", "store": "Obchod", "selectStore": "Vyberte obchod", "viewStoreCta": "Zobrazit obchod a naplánovat návštěvu", "forCustomers": "Pro zákazníky", "customersText": "Se <strong>Scheduled Visit Discount (SVD)</strong> si předem naplánujete návštěvu obchodu. Pokud dorazíte včas a nakoupíte, získáte předem dohodnutou slevu. Žádné čekání, žádná nejistota, lepší ceny.", "forStoreManagers": "Pro majitele obchodů", "managersText": "SVD mění plánované návštěvy v předvídatelnou poptávku. Víte, kdo přijde, kdy a proč. Slevy jsou vyváženy vyšší konverzí, plynulejším provozem a lepším využitím personálu a prostoru.", "heroHeadline": "Slevy neprodávají.", "heroAccent": "Závazek ano.", "heroSubline": "Proměňte okounějící kolemjdoucí ve věrné zákazníky."}}
'@

$files["sk"] = @'
{"HomePage": {"scheduleHeading": "Naplánujte návštevu a získajte zľavu", "country": "Krajina", "selectCountry": "Vyberte krajinu", "city": "Mesto", "selectCity": "Vyberte mesto", "store": "Obchod", "selectStore": "Vyberte obchod", "viewStoreCta": "Zobraziť obchod a naplánovať návštevu", "forCustomers": "Pre zákazníkov", "customersText": "So <strong>Scheduled Visit Discount (SVD)</strong> si vopred naplánujete návštevu obchodu. Ak prídete včas a nakúpite, dostanete vopred dohodnutú zľavu. Žiadne čakanie, žiadna neistota, lepšie ceny.", "forStoreManagers": "Pre majiteľov obchodov", "managersText": "SVD mení plánované návštevy na predvídateľný dopyt. Viete, kto príde, kedy a prečo. Zľavy vyvažuje vyššia konverzia, plynulejšia prevádzka a lepšie využitie personálu a priestoru.", "heroHeadline": "Zľavy nepredávajú.", "heroAccent": "Záväzok áno.", "heroSubline": "Premeňte okoloidúcich na oddaných zákazníkov."}}
'@

$files["hu"] = @'
{"HomePage": {"scheduleHeading": "Foglalj időpontot és kapj kedvezményt", "country": "Ország", "selectCountry": "Válassz országot", "city": "Város", "selectCity": "Válassz várost", "store": "Bolt", "selectStore": "Válassz boltot", "viewStoreCta": "Bolt megtekintése és időpontfoglalás", "forCustomers": "Vásárlóknak", "customersText": "A <strong>Scheduled Visit Discount (SVD)</strong> segítségével előre lefoglalod a boltlátogatást. Ha időben megérkezel és vásárolsz, előre egyeztetett kedvezményt kapsz. Nincs várakozás, nincs bizonytalanság, jobb árak.", "forStoreManagers": "Boltosoknak", "managersText": "Az SVD a tervezett látogatásokat kiszámítható kereslet teszi. Tudod, ki jön, mikor és miért. A kedvezményeket ellensúlyozza a magasabb konverzió, a zökkenőmentesebb működés és a személyzet és a tér jobb kihasználása.", "heroHeadline": "A kedvezmények nem adnak el.", "heroAccent": "Az elköteleződés igen.", "heroSubline": "Változtasd az ablaknézegetőket elkötelezett vásárlókká."}}
'@

$files["sl"] = @'
{"HomePage": {"scheduleHeading": "Rezervirajte obisk in prejmite popust", "country": "Država", "selectCountry": "Izberite državo", "city": "Mesto", "selectCity": "Izberite mesto", "store": "Trgovina", "selectStore": "Izberite trgovino", "viewStoreCta": "Ogled trgovine in rezervacija obiska", "forCustomers": "Za stranke", "customersText": "S <strong>Scheduled Visit Discount (SVD)</strong> vnaprej rezervirate obisk trgovine. Če pridete pravočasno in opravite nakup, prejmete vnaprej dogovorjen popust. Brez čakanja, brez negotovosti, boljše cene.", "forStoreManagers": "Za lastnike trgovin", "managersText": "SVD spremeni načrtovane obiske v predvidljivo povpraševanje. Veste, kdo prihaja, kdaj in zakaj. Popuste izravnajo večja konverzija, bolj tekoče poslovanje in boljša izraba osebja in prostora.", "heroHeadline": "Popusti ne prodajajo.", "heroAccent": "Zaveza pa.", "heroSubline": "Spremenite ogledovalce izložb v zaveze polne stranke."}}
'@

$files["ro"] = @'
{"HomePage": {"scheduleHeading": "Programează o vizită și primești o reducere", "country": "Țară", "selectCountry": "Selectează țara", "city": "Oraș", "selectCity": "Selectează orașul", "store": "Magazin", "selectStore": "Selectează magazinul", "viewStoreCta": "Vezi magazinul și programează vizita", "forCustomers": "Pentru clienți", "customersText": "Cu <strong>Scheduled Visit Discount (SVD)</strong>, programezi o vizită la magazin în avans. Dacă ajungi la timp și faci o achiziție, primești o reducere stabilită în prealabil. Fără așteptare, fără incertitudine, prețuri mai bune.", "forStoreManagers": "Pentru comercianți", "managersText": "SVD transformă vizitele planificate în cerere previzibilă. Știi cine vine, când și de ce. Reducerile sunt compensate de o conversie mai mare, operațiuni mai fluide și o utilizare mai bună a personalului și a spațiului.", "heroHeadline": "Reducerile nu vând.", "heroAccent": "Angajamentul da.", "heroSubline": "Transformă privitorii vitrinelor în clienți fideli."}}
'@

$files["sr"] = @'
{"HomePage": {"scheduleHeading": "Закажите посету и добијте попуст", "country": "Држава", "selectCountry": "Изаберите државу", "city": "Град", "selectCity": "Изаберите град", "store": "Продавница", "selectStore": "Изаберите продавницу", "viewStoreCta": "Погледајте продавницу и закажите посету", "forCustomers": "За купце", "customersText": "Уз <strong>Scheduled Visit Discount (SVD)</strong>, унапред закажете посету продавници. Ако стигнете на време и обавите куповину, добијате унапред договорен попуст. Без чекања, без неизвесности, боље цене.", "forStoreManagers": "За власнике продавница", "managersText": "SVD претвара планиране посете у предвидиву тражњу. Знате ко долази, када и зашто. Попусти се компензују већом конверзијом, глаткијим пословањем и бољим коришћењем особља и простора.", "heroHeadline": "Попусти не продају.", "heroAccent": "Посвећеност продаје.", "heroSubline": "Претворите знатижељне пролазнике у посвећене купце."}}
'@

$files["hr"] = @'
{"HomePage": {"scheduleHeading": "Rezervirajte posjet i ostvarite popust", "country": "Država", "selectCountry": "Odaberite državu", "city": "Grad", "selectCity": "Odaberite grad", "store": "Trgovina", "selectStore": "Odaberite trgovinu", "viewStoreCta": "Pogledaj trgovinu i rezerviraj posjet", "forCustomers": "Za kupce", "customersText": "Uz <strong>Scheduled Visit Discount (SVD)</strong>, unaprijed rezervirate posjet trgovini. Ako stignete na vrijeme i obavite kupnju, dobivate unaprijed dogovoren popust. Bez čekanja, bez neizvjesnosti, bolje cijene.", "forStoreManagers": "Za vlasnike trgovina", "managersText": "SVD pretvara planirane posjete u predvidljivu potražnju. Znate tko dolazi, kada i zašto. Popusti se nadoknađuju većom konverzijom, glatkijim poslovanjem i boljim korištenjem osoblja i prostora.", "heroHeadline": "Popusti ne prodaju.", "heroAccent": "Predanost da.", "heroSubline": "Pretvorite znatiželjne prolaznike u predane kupce."}}
'@

$files["bg"] = @'
{"HomePage": {"scheduleHeading": "Запазете посещение и получете отстъпка", "country": "Държава", "selectCountry": "Изберете държава", "city": "Град", "selectCity": "Изберете град", "store": "Магазин", "selectStore": "Изберете магазин", "viewStoreCta": "Вижте магазина и запазете посещение", "forCustomers": "За клиенти", "customersText": "С <strong>Scheduled Visit Discount (SVD)</strong> вие предварително запазвате посещение в магазина. Ако пристигнете навреме и направите покупка, получавате предварително договорена отстъпка. Без чакане, без несигурност, по-добри цени.", "forStoreManagers": "За собственици на магазини", "managersText": "SVD превръща планираните посещения в предвидимо търсене. Знаете кой идва, кога и защо. Отстъпките се компенсират с по-висока конверсия, по-гладка работа и по-добро използване на персонала и пространството.", "heroHeadline": "Отстъпките не продават.", "heroAccent": "Ангажираността продава.", "heroSubline": "Превърнете зяпащите витрини в отдадени клиенти."}}
'@

$files["sq"] = @'
{"HomePage": {"scheduleHeading": "Rezervoni një vizitë dhe merrni një zbritje", "country": "Shteti", "selectCountry": "Zgjidhni shtetin", "city": "Qyteti", "selectCity": "Zgjidhni qytetin", "store": "Dyqani", "selectStore": "Zgjidhni dyqanin", "viewStoreCta": "Shiko dyqanin dhe rezervo vizitën", "forCustomers": "Për klientët", "customersText": "Me <strong>Scheduled Visit Discount (SVD)</strong>, rezervoni një vizitë në dyqan paraprakisht. Nëse arrini në kohë dhe bëni një blerje, merrni një zbritje të rënë dakord paraprakisht. Pa pritje, pa pasiguri, çmime më të mira.", "forStoreManagers": "Për pronarët e dyqaneve", "managersText": "SVD i shndërron vizitat e planifikuara në kërkesë të parashikueshme. E dini kush vjen, kur dhe pse. Zbritjet kompensohen nga konvertimi më i lartë, funksionimi më i qetë dhe përdorimi më i mirë i stafit dhe hapësirës.", "heroHeadline": "Zbritjet nuk shesin.", "heroAccent": "Angazhimi po.", "heroSubline": "Shndërroni kalimtarët kureshtarë në klientë të angazhuar."}}
'@

$files["uk"] = @'
{"HomePage": {"scheduleHeading": "Забронюйте візит і отримайте знижку", "country": "Країна", "selectCountry": "Виберіть країну", "city": "Місто", "selectCity": "Виберіть місто", "store": "Магазин", "selectStore": "Виберіть магазин", "viewStoreCta": "Переглянути магазин і забронювати візит", "forCustomers": "Для клієнтів", "customersText": "Завдяки <strong>Scheduled Visit Discount (SVD)</strong> ви заздалегідь бронюєте візит до магазину. Якщо ви приходите вчасно і робите покупку, отримуєте заздалегідь узгоджену знижку. Без очікування, без невизначеності, кращі ціни.", "forStoreManagers": "Для власників магазинів", "managersText": "SVD перетворює заплановані візити на прогнозований попит. Ви знаєте, хто прийде, коли і чому. Знижки компенсуються вищою конверсією, плавнішою роботою та кращим використанням персоналу й простору.", "heroHeadline": "Знижки не продають.", "heroAccent": "Віддана продає.", "heroSubline": "Перетворіть допитливих перехожих на відданих клієнтів."}}
'@

$files["ru"] = @'
{"HomePage": {"scheduleHeading": "Забронируйте визит и получите скидку", "country": "Страна", "selectCountry": "Выберите страну", "city": "Город", "selectCity": "Выберите город", "store": "Магазин", "selectStore": "Выберите магазин", "viewStoreCta": "Посмотреть магазин и забронировать визит", "forCustomers": "Для покупателей", "customersText": "С <strong>Scheduled Visit Discount (SVD)</strong> вы заранее бронируете визит в магазин. Если вы приходите вовремя и совершаете покупку, получаете заранее оговорённую скидку. Никакого ожидания, никакой неопределённости, лучшие цены.", "forStoreManagers": "Для владельцев магазинов", "managersText": "SVD превращает запланированные визиты в предсказуемый спрос. Вы знаете, кто придёт, когда и почему. Скидки компенсируются более высокой конверсией, более плавной работой и лучшим использованием персонала и пространства.", "heroHeadline": "Скидки не продают.", "heroAccent": "Обязательство продаёт.", "heroSubline": "Превратите любопытных прохожих в преданных клиентов."}}
'@

$files["ka"] = @'
{"HomePage": {"scheduleHeading": "დაჯავშნეთ ვიზიტი და მიიღეთ ფასდაკლება", "country": "ქვეყანა", "selectCountry": "აირჩიეთ ქვეყანა", "city": "ქალაქი", "selectCity": "აირჩიეთ ქალაქი", "store": "მაღაზია", "selectStore": "აირჩიეთ მაღაზია", "viewStoreCta": "ნახეთ მაღაზია და დაჯავშნეთ ვიზიტი", "forCustomers": "მომხმარებლებისთვის", "customersText": "<strong>Scheduled Visit Discount (SVD)</strong>-ის საშუალებით წინასწარ ჯავშნით მაღაზიის ვიზიტს. თუ დროულად ჩამოხვალთ და შეიძენთ, მიიღებთ წინასწარ შეთანხმებულ ფასდაკლებას. ლოდინის და გაურკვევლობის გარეშე, უკეთესი ფასები.", "forStoreManagers": "მაღაზიის მფლობელებისთვის", "managersText": "SVD გეგმიურ ვიზიტებს პროგნოზირებად მოთხოვნად აქცევს. იცით ვინ მოვა, როდის და რატომ. ფასდაკლებებს აბალანსებს უფრო მაღალი კონვერსია, უფრო გამართული მუშაობა და პერსონალისა და სივრცის უკეთესი გამოყენება.", "heroHeadline": "ფასდაკლებები არ ყიდის.", "heroAccent": "ვალდებულება ყიდის.", "heroSubline": "აქციეთ ვიტრინის მაყურებლები ერთგულ მომხმარებლებად."}}
'@

$files["tr"] = @'
{"HomePage": {"scheduleHeading": "Ziyaret planlayın ve indirim kazanın", "country": "Ülke", "selectCountry": "Ülke seçin", "city": "Şehir", "selectCity": "Şehir seçin", "store": "Mağaza", "selectStore": "Mağaza seçin", "viewStoreCta": "Mağazayı görüntüle ve ziyaret planla", "forCustomers": "Müşteriler için", "customersText": "<strong>Scheduled Visit Discount (SVD)</strong> ile mağaza ziyaretinizi önceden planlarsınız. Zamanında gelip alışveriş yaparsanız, önceden anlaşılan bir indirim alırsınız. Bekleme yok, belirsizlik yok, daha iyi fiyatlar.", "forStoreManagers": "Mağaza sahipleri için", "managersText": "SVD, planlanan ziyaretleri öngörülebilir talebe dönüştürür. Kimin, ne zaman ve neden geldiğini bilirsiniz. İndirimler, daha yüksek dönüşüm, daha sorunsuz işleyiş ve personel ile alanın daha iyi kullanımıyla dengelenir.", "heroHeadline": "İndirimler satmaz.", "heroAccent": "Bağlılık satar.", "heroSubline": "Vitrin bakanları bağlı müşterilere dönüştürün."}}
'@

$files["ja"] = @'
{"HomePage": {"scheduleHeading": "来店予約をして割引を受け取る", "country": "国", "selectCountry": "国を選択", "city": "都市", "selectCity": "都市を選択", "store": "店舗", "selectStore": "店舗を選択", "viewStoreCta": "店舗を見て来店予約する", "forCustomers": "お客様へ", "customersText": "<strong>Scheduled Visit Discount(SVD)</strong>を利用すると、事前に来店予約ができます。予約時間通りに来店し購入すると、事前に決められた割引が受けられます。待ち時間も不安もなく、より良い価格で。", "forStoreManagers": "店舗オーナー様へ", "managersText": "SVDは予定された来店を予測可能な需要に変えます。誰が、いつ、なぜ来店するかが分かります。割引は、より高い成約率、スムーズな運営、スタッフとスペースの有効活用によって相殺されます。", "heroHeadline": "割引だけでは売れません。", "heroAccent": "コミットメントが売ります。", "heroSubline": "ウィンドウショッパーをコミットした顧客へ。"}}
'@

$files["ko"] = @'
{"HomePage": {"scheduleHeading": "방문을 예약하고 할인을 받으세요", "country": "국가", "selectCountry": "국가 선택", "city": "도시", "selectCity": "도시 선택", "store": "매장", "selectStore": "매장 선택", "viewStoreCta": "매장 보기 및 방문 예약", "forCustomers": "고객을 위해", "customersText": "<strong>Scheduled Visit Discount(SVD)</strong>를 이용하면 매장 방문을 미리 예약할 수 있습니다. 제시간에 도착하여 구매하면 사전에 합의된 할인을 받습니다. 기다림도, 불확실함도 없이 더 나은 가격으로.", "forStoreManagers": "매장 운영자를 위해", "managersText": "SVD는 예정된 방문을 예측 가능한 수요로 바꿉니다. 누가, 언제, 왜 오는지 알 수 있습니다. 할인은 더 높은 전환율, 더 원활한 운영, 인력과 공간의 더 나은 활용으로 상쇄됩니다.", "heroHeadline": "할인은 팔리지 않습니다.", "heroAccent": "헌신은 팔립니다.", "heroSubline": "쇼윈도 구경꾼을 헌신적인 고객으로."}}
'@

$files["zh"] = @'
{"HomePage": {"scheduleHeading": "预约到店并获得折扣", "country": "国家", "selectCountry": "选择国家", "city": "城市", "selectCity": "选择城市", "store": "商店", "selectStore": "选择商店", "viewStoreCta": "查看商店并预约到店", "forCustomers": "顾客专区", "customersText": "通过<strong>预约到店折扣（SVD）</strong>，您可以提前预约到店。只要准时到达并完成购买，即可获得事先约定的折扣。无需等待，无需猜测，价格更优。", "forStoreManagers": "商家专区", "managersText": "SVD 将计划中的到店转化为可预测的需求。您知道谁会来、何时来、为何而来。折扣带来的成本会被更高的转化率、更顺畅的运营以及更有效的人员与空间利用所抵消。", "heroHeadline": "折扣本身不会带来销量。", "heroAccent": "承诺才会。", "heroSubline": "把随便看看的路人变成忠实顾客。"}}
'@

$files["hi"] = @'
{"HomePage": {"scheduleHeading": "विज़िट बुक करें और छूट पाएं", "country": "देश", "selectCountry": "देश चुनें", "city": "शहर", "selectCity": "शहर चुनें", "store": "स्टोर", "selectStore": "स्टोर चुनें", "viewStoreCta": "स्टोर देखें और विज़िट बुक करें", "forCustomers": "ग्राहकों के लिए", "customersText": "<strong>Scheduled Visit Discount (SVD)</strong> के साथ, आप पहले से स्टोर विज़िट बुक करते हैं। अगर आप समय पर पहुंचते हैं और खरीदारी करते हैं, तो आपको पहले से तय की गई छूट मिलती है। कोई इंतज़ार नहीं, कोई अनिश्चितता नहीं, बेहतर कीमतें।", "forStoreManagers": "स्टोर मालिकों के लिए", "managersText": "SVD योजनाबद्ध विज़िट को पूर्वानुमानित मांग में बदल देता है। आप जानते हैं कि कौन आ रहा है, कब और क्यों। छूट की भरपाई अधिक कन्वर्ज़न, सुचारू संचालन और स्टाफ व स्थान के बेहतर उपयोग से होती है।", "heroHeadline": "छूट से बिक्री नहीं होती।", "heroAccent": "प्रतिबद्धता से होती है।", "heroSubline": "खिड़की देखने वालों को प्रतिबद्ध ग्राहकों में बदलें।"}}
'@

$files["ms"] = @'
{"HomePage": {"scheduleHeading": "Tempah lawatan dan dapatkan diskaun", "country": "Negara", "selectCountry": "Pilih negara", "city": "Bandar", "selectCity": "Pilih bandar", "store": "Kedai", "selectStore": "Pilih kedai", "viewStoreCta": "Lihat kedai dan tempah lawatan", "forCustomers": "Untuk pelanggan", "customersText": "Dengan <strong>Scheduled Visit Discount (SVD)</strong>, anda menempah lawatan kedai lebih awal. Jika anda tiba tepat pada masanya dan membuat pembelian, anda akan menerima diskaun yang telah dipersetujui. Tiada menunggu, tiada ketidakpastian, harga yang lebih baik.", "forStoreManagers": "Untuk pemilik kedai", "managersText": "SVD menukar lawatan yang dirancang kepada permintaan yang boleh diramal. Anda tahu siapa yang datang, bila dan mengapa. Diskaun diimbangi oleh penukaran yang lebih tinggi, operasi yang lebih lancar dan penggunaan kakitangan serta ruang yang lebih baik.", "heroHeadline": "Diskaun tidak menjual.", "heroAccent": "Komitmen menjual.", "heroSubline": "Tukar pemerhati tingkap menjadi pelanggan komited."}}
'@

$files["id"] = @'
{"HomePage": {"scheduleHeading": "Jadwalkan kunjungan dan dapatkan diskon", "country": "Negara", "selectCountry": "Pilih negara", "city": "Kota", "selectCity": "Pilih kota", "store": "Toko", "selectStore": "Pilih toko", "viewStoreCta": "Lihat toko dan jadwalkan kunjungan", "forCustomers": "Untuk pelanggan", "customersText": "Dengan <strong>Scheduled Visit Discount (SVD)</strong>, Anda memesan kunjungan toko terlebih dahulu. Jika Anda tiba tepat waktu dan melakukan pembelian, Anda mendapatkan diskon yang telah disepakati sebelumnya. Tanpa menunggu, tanpa ketidakpastian, harga lebih baik.", "forStoreManagers": "Untuk pemilik toko", "managersText": "SVD mengubah kunjungan terjadwal menjadi permintaan yang dapat diprediksi. Anda tahu siapa yang datang, kapan, dan mengapa. Diskon diimbangi oleh konversi yang lebih tinggi, operasi yang lebih lancar, dan penggunaan staf serta ruang yang lebih baik.", "heroHeadline": "Diskon tidak menjual.", "heroAccent": "Komitmen yang menjual.", "heroSubline": "Ubah pengunjung etalase menjadi pelanggan setia."}}
'@

$files["tl"] = @'
{"HomePage": {"scheduleHeading": "Mag-book ng bisita at kumuha ng diskwento", "country": "Bansa", "selectCountry": "Piliin ang bansa", "city": "Lungsod", "selectCity": "Piliin ang lungsod", "store": "Tindahan", "selectStore": "Piliin ang tindahan", "viewStoreCta": "Tingnan ang tindahan at mag-book ng bisita", "forCustomers": "Para sa mga customer", "customersText": "Gamit ang <strong>Scheduled Visit Discount (SVD)</strong>, nagbo-book ka ng bisita sa tindahan nang maaga. Kung darating ka sa tamang oras at bibili, makakakuha ka ng dating napagkasunduang diskwento. Walang paghihintay, walang kawalang-katiyakan, mas magandang presyo.", "forStoreManagers": "Para sa mga may-ari ng tindahan", "managersText": "Ginagawa ng SVD ang mga naka-iskedyul na bisita na predictable na demand. Alam mo kung sino ang darating, kailan, at bakit. Ang mga diskwento ay nabalanse ng mas mataas na conversion, mas maayos na operasyon, at mas mahusay na paggamit ng staff at espasyo.", "heroHeadline": "Hindi nagbebenta ang diskwento.", "heroAccent": "Ang commitment, oo.", "heroSubline": "Gawing committed customers ang mga window-shopper."}}
'@

$files["he"] = @'
{"HomePage": {"scheduleHeading": "קבעו ביקור וקבלו הנחה", "country": "מדינה", "selectCountry": "בחרו מדינה", "city": "עיר", "selectCity": "בחרו עיר", "store": "חנות", "selectStore": "בחרו חנות", "viewStoreCta": "צפו בחנות וקבעו ביקור", "forCustomers": "ללקוחות", "customersText": "עם <strong>Scheduled Visit Discount (SVD)</strong>, אתם קובעים ביקור בחנות מראש. אם תגיעו בזמן ותבצעו רכישה, תקבלו הנחה שסוכמה מראש. בלי המתנה, בלי אי-ודאות, מחירים טובים יותר.", "forStoreManagers": "לבעלי חנויות", "managersText": "SVD הופך ביקורים מתוכננים לביקוש צפוי. אתם יודעים מי מגיע, מתי ולמה. ההנחות מקוזזות בהמרה גבוהה יותר, פעילות חלקה יותר וניצול טוב יותר של הצוות והמרחב.", "heroHeadline": "הנחות לא מוכרות.", "heroAccent": "מחויבות כן.", "heroSubline": "הפכו מסתכלים בחלון ללקוחות מחויבים."}}
'@

$files["ar"] = @'
{"HomePage": {"scheduleHeading": "احجز زيارة واحصل على خصم", "country": "الدولة", "selectCountry": "اختر الدولة", "city": "المدينة", "selectCity": "اختر المدينة", "store": "المتجر", "selectStore": "اختر المتجر", "viewStoreCta": "عرض المتجر وحجز الزيارة", "forCustomers": "للعملاء", "customersText": "من خلال <strong>Scheduled Visit Discount (SVD)</strong>، تحجز زيارة للمتجر مسبقًا. إذا وصلت في الوقت المحدد وأجريت عملية شراء، تحصل على خصم متفق عليه مسبقًا. بلا انتظار، بلا شك، أسعار أفضل.", "forStoreManagers": "لأصحاب المتاجر", "managersText": "يحوّل SVD الزيارات المخطط لها إلى طلب يمكن التنبؤ به. تعرف من سيأتي، ومتى، ولماذا. يتم تعويض الخصومات بمعدل تحويل أعلى، وعمليات أكثر سلاسة، واستخدام أفضل للموظفين والمساحة.", "heroHeadline": "الخصومات لا تبيع.", "heroAccent": "الالتزام يبيع.", "heroSubline": "حوّل المتفرجين على الواجهات إلى عملاء ملتزمين."}}
'@

$files["fa"] = @'
{"HomePage": {"scheduleHeading": "بازدید را رزرو کنید و تخفیف بگیرید", "country": "کشور", "selectCountry": "کشور را انتخاب کنید", "city": "شهر", "selectCity": "شهر را انتخاب کنید", "store": "فروشگاه", "selectStore": "فروشگاه را انتخاب کنید", "viewStoreCta": "مشاهده فروشگاه و رزرو بازدید", "forCustomers": "برای مشتریان", "customersText": "با <strong>Scheduled Visit Discount (SVD)</strong>، از قبل بازدید از فروشگاه را رزرو می‌کنید. اگر به موقع برسید و خرید کنید، تخفیف از پیش توافق‌شده دریافت می‌کنید. بدون انتظار، بدون عدم قطعیت، قیمت‌های بهتر.", "forStoreManagers": "برای مالکان فروشگاه", "managersText": "SVD بازدیدهای برنامه‌ریزی‌شده را به تقاضای قابل پیش‌بینی تبدیل می‌کند. می‌دانید چه کسی، چه زمانی و چرا می‌آید. تخفیف‌ها با نرخ تبدیل بالاتر، عملیات روان‌تر و استفاده بهتر از کارکنان و فضا جبران می‌شوند.", "heroHeadline": "تخفیف‌ها نمی‌فروشند.", "heroAccent": "تعهد می‌فروشد.", "heroSubline": "تماشاگران ویترین را به مشتریان متعهد تبدیل کنید."}}
'@

foreach ($code in $files.Keys) {
    $path = Join-Path $dir "$code.json"
    Write-Utf8NoBom -Path $path -Content $files[$code]
}

Write-Host ""
Write-Host "Done. Created $($files.Count) files in .\$dir\"